### PR TITLE
Add additional paths

### PR DESCRIPTION
**Pull request by aschuster3**
Just a quick PR to add a handful of additional endpoints

### CODE REVIEW

**Comment by MatUrbanski** [comment]
Hey, Thanks for contributing to athena_health gem. Specs are not passing, could You fix it?

**Comment by aschuster3** [comment]
Forgot a comma

Classic mistake

**Comment by MatUrbanski** [comment]
Those new endpoints are not tested. Could you add tests for that?

**Comment by aschuster3** [comment]
Ah, sorry about that, completely overlooked the tests, I'll get that out soon

**Comment by MatUrbanski** [comment]
Looks good.

**Pull request merged**
